export const FUNNY_NAMES: Record<string, string> = {
	demonzz1: "gucio_waiting_room",
	jaskol95: "oszust95",
	nieuczesana: "Niewyczochrana",
	slayproxx: "Slayproxx (Adam)",
	bonkol: "Bencoal",
	randombrucetv: "MedikinetTV",
	mokrysuchar: "MokrySocjopata",
	meduska: "KongoTV",
	xntentacion: "xnxxtentacion",
	adamcy: "po_co_tu_wbijasz_jak_on_i_tak_znowu_oszuka_widzow",
	furazek: "Bazyl",
	mamm0n: "Mamm0n_fan_Tubsona",
	tubson: "Tubson_fan_Mamm0na",
	tubson_: "Tubson_fan_Mamm0na",
	olszakumpel: "olszaprzyjaciel",
	youngmulti: "Needyourblood",
	menders_7: "Menels_7",
	lequt: "OmeTV_PL_Konto_Oficjalne",
	edenitoo: "zakolak",
	delord: "delmniak",
};

export const FUNNY_IMAGES: Record<string, string> = {
	arquel: "https://cdn-badges.enhancer.at/funny-avatars/arquel.png",
	gambit_florydy: "https://cdn-badges.enhancer.at/funny-avatars/gambit_florydy.png",
	h2p_gucio: "https://cdn-badges.enhancer.at/funny-avatars/h2p_gucio.png",
	jaskol95: "https://cdn-badges.enhancer.at/funny-avatars/jaskol95.png",
	meduska: "https://cdn-badges.enhancer.at/funny-avatars/meduska.jpg",
	adamcy: "https://cdn-badges.enhancer.at/funny-avatars/obiecuje.jpg",
	xntentacion: "https://cdn-badges.enhancer.at/funny-avatars/xntentacion.jpg",
};
