export const FUNNY_NAMES: Record<string, string> = {
	igorovh: "igor nowak",
	demonzz1: "gucio_waiting_room",
	jaskol95: "oszust95",
	nieuczesana: "Niewyczochrana",
	slayproxx: "Adamproxx",
	bonkol: "Bencoal",
	randombrucetv: "MedikinetTV",
	overpow: "RandomOverpowTV",
	mokrysuchar: "MokrySocjopata",
	meduska: "KongoTV",
	xntentacion: "xnxxtentacion",
	adamcy: "po co tu wbijasz jak i tak rudy znowu oszuka",
	franio: "WymoczekTV",
	furazek: "Bazylius Kwiekus",
	mamm0n: "Mamm0n_fan_Tubsona",
	tubson: "Tubson_fan_Mamm0na",
	tubson_: "Tubson_fan_Mamm0na",
	olszakumpel: "olszaprzyjaciel",
	youngmulti: "MultiGameplayGuy",
	menders_7: "Menels_7",
	lequt: "OmeTV_PL_Konto_Oficjalne",
	edenitoo: "zakolitoo",
	delordione: "delmito",
	mlekosz666: "Mlekoś",
	tomekpi: "tomekpl_no_nie?",
	maquk: "mamamamaquk",
	rybsonlol: "kolega xayoo",
	banduracartel: "BOKS",
	mrdzinold: "STOP",
	xayoo: "Legenda",
	lewus: "Matura z Lewusem",
	veniakk: "Łoniakk",
	stasieklive: "nieśmiały typ",
	ewroon: "Erwin Knuckles",
	ewron: "Erwin Knuckles",
	gruby_macko: "chudy_macko",
	pohisa: "Kaktus Jacek",
	yerwi25: "Minusik",
	x3te: "łajza^2",
	pozdrawiam_wegorza: "nakurwiamwegorza",
	timon20: "aftersun20",
	tomekasa: "tomekasa_ssie...",
	dlawek: "slavek🟦🟨",
	conkii_: "łajza",
	diables: "chłopak Nieuczesanej",
	pajalock: "Pathyk",
	zarber_: "dziabko :3",
};

export const FUNNY_AVATARS: Record<string, string> = {
	arquel: "https://cdn-badges.enhancer.at/funny-avatars/arquel.png",
	gambit_florydy: "https://cdn-badges.enhancer.at/funny-avatars/gambit_florydy.png",
	h2p_gucio: "https://cdn-badges.enhancer.at/funny-avatars/h2p_gucio.png",
	jaskol95: "https://cdn-badges.enhancer.at/funny-avatars/jaskol95.png",
	meduska: "https://cdn-badges.enhancer.at/funny-avatars/meduska.jpg",
	adamcy: "https://cdn-badges.enhancer.at/funny-avatars/obiecuje.png",
	xntentacion: "https://cdn-badges.enhancer.at/funny-avatars/xntentacion.png",
	rybsonlol: "https://cdn-badges.enhancer.at/funny-avatars/rybson.jpg",
};

export const FUNNY_TITLES: Record<string, string> = {
	h2p_gucio: "dzisiaj RDR2 z lektorem o 19, obiecuje na zozo",
	demonzz1: "dzisiaj baldurs gate 3, aż Gucio nie odpali, jak potem skończy to odpalamy cannibal holo. Pozdrawiam <3",
	gambit_florydy: "DZISIAJ WYPUSZCZAMY PODSUMOWANIE ROKU 🔴 WCALE NIE SPÓŻNIONE 🔴 !dzik #ad",
	pajalock: "DZISIAJ OŚWIADCZAM SIĘ EWIE | 📅 DZIEŃ 67 | #reklama",
	slayproxx: "test",
};

export const FUNNY_CATEGORIES: Record<string, string> = {
	h2p_gucio: "Red Dead Redemption 2",
};

export const FUNNY_TOOLTIPS: Record<string, string> = {
	demonzz1: "was changed by the user H2P_Gucio",
	adamcy: "was changed by the Niebo Sigma",
};
