name: Merge master to develop

on:
  push:
    branches:
      - master

jobs:
  merge-master-to-develop:
    name: Merge master to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.ENHANCER_BOT_TOKEN }}

      - name: Merge Master into Develop
        run: |
          git config --global user.name "Enhancer Bot"
          git config --global user.email "${{ secrets.ENHANCER_BOT_EMAIL }}"

          git merge origin/master --no-edit

          if [ -z "$(git status --porcelain)" ]; then
             echo "Nothing to push (Develop is already up to date)."
          else
             git push origin develop
             echo "Successfully pushed updates to Develop."
          fi