name: Release

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [edited]
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: release-pr
  cancel-in-progress: true

jobs:
  release-pr:
    name: Update release PR
    if: >-
      github.event_name == 'push' ||
      (github.event.pull_request.head.ref == 'release/next' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.changes.body)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      checks: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Create or update release PR
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            const run = require("./.github/scripts/release-pr.cjs");
            await run({ github, context, core, exec });
